### ISSUE TITLE
能否支持一下python2

### ISSUE THREAD

**Issue by ghost** [imliuda/aliyun-sms#1]
公司的项目还没有升级到python3.

**Comment by ghost** [comment]
而且最新的项目里面似乎可以直接用app_code.而不需要用key和secret做hmac...https://gist.github.com/tyan4g/c01728dcc91298195c6b3f1706fce7a2

**Comment by imliuda** [comment]
不好意思 没注意到 这个接口不难的 你可以稍微改下就可以了
